# Generated by Django 5.0.3 on 2024-05-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemekke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('additional_notes', models.TextField(blank=True, max_length=150, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='yemekke.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yemekke.product')),
            ],
        ),
    ]
