# Generated by Django 5.0.3 on 2024-05-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemekke', '0003_rename_restoranuser_selleruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yemekke.user'),
        ),
    ]
